#Default Configuration File for JoshCraft 2.5
Recipe:
  Leather:
    Enabled: true
    FleshForLeather: 4
  HorseArmor:
    Iron: true
    Gold: true
    Diamond: true
  Saddle: true
  Nametag: true
Spawn:
  Giant:
    Max: 0
    Message: Fee Fi Fo Fum
  Wither:
    Max: 0
    Message: The air chills, The flora withers... a new presence emerges