#Default Configuration File for JoshCraft 2.5
Recipe:
  Leather:
    Enabled: true
    FleshForLeather: 4
  HorseArmor:
    Iron: true
    Gold: true
    Diamond: true
  Saddle: true
  Nametag: true
Spawn:
  Giant: false