#Default Configuration File for JoshCraft 3.0.1Dev
Recipe:
  Leather:
    Enabled: true
    FleshForLeather: 4
  HorseArmor:
    Iron: true
    Gold: true
    Diamond: true
  Saddle: true
  Nametag: true
  Ice: true
  Sponge: true
  Misc: false
Spawn:
  Giant:
    Max: 0
    SpawnNumerator: 1
    SpawnDenominator: 1000
    Message: Fee Fi Fo Fum...
