name: JeevesCraft
main: com.github.abujaki21.jeevesCraft.JeevesCraft
version: 2.8 Halloween
description: A collection of fixes and spooks used for the Jeeves server
author: abujaki21
website: https://github.com/abujaki21/jeevescraft